### ISSUE TITLE
cmake throws Warnings like "Ignoring extra path from command line:"

### ISSUE THREAD

**Issue by AxelG-DE** [jade-nl/dt.bldr#26]
**Is your feature request related to a problem? Please describe.**
I can build fine, however in the logs I found:

```
Already up to date.
Skipping submodule 'src/tests/integration'
CMake Warning:
  Ignoring extra path from command line:

   "/home/gerber/.local/git/darktable/build/CMAKE_C_FLAGS=-march=native -O2 -mtune=native -pipe"


CMake Warning:
  Ignoring extra path from command line:

   "CMAKE_CXX_FLAGS=-march=native -O2 -mtune=native -pipe"


-- The CXX compiler identification is GNU 13.2.1
-- The C compiler identification is GNU 13.2.1
-- Detecting CXX compiler ABI info

```

**Describe the solution you'd like**
After asking on IRC #gentoo, I got the hint to prepend -D and I did so in /opt/dt.bldr/bin/dt.bldr.sh, lines 298 and 299, so they look now:

```
297         -DTESTBUILD_OPENCL_PROGRAMS="${TESTBUILD_OPENCL_PROGRAMS}" \
298         -DCMAKE_C_FLAGS="${CMAKE_FLAGS}" \
299         -DCMAKE_CXX_FLAGS="${CMAKE_FLAGS}" \
300         -G "${cmakeGen}" \
```

weird thing is, I am missing the first lines (_already up to date_ and _Skipping ... _
```
-- The CXX compiler identification is GNU 13.2.1
-- The C compiler identification is GNU 13.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
```

**Additional context**
OS:    gentoo
cmake-version:   3.26.5

**Comment by AxelG-DE** [comment]
update: just now ran a "classical" run with no options invoked as done for years and log looks good to me:

[dt.build.1000.2023.10.13.2015.log.zip](https://github.com/jade-nl/dt.bldr/files/12897244/dt.build.1000.2023.10.13.2015.log.zip)

**Comment by jade-nl** [comment]
Thanks for the heads-up

Issue is now fixed.
